#!/usr/bin/env bash

if [ "$1" != "" ]; then
	echo "Compilind and Run code java"
	ext=.java
	javac $1$ext
	java $1
else
	echo "JC script parameter 1 is empty"
	echo "usage: "
	echo "jc <NameOfFileOnly>"
fi
